# Generated by Django 5.1.5 on 2025-01-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('indicador', models.CharField(max_length=100, unique=True)),
                ('formula', models.CharField(max_length=100, unique=True)),
                ('frecuencia', models.IntegerField()),
                ('verificacion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medida', models.ForeignKey(db_column='id_medida', on_delete=django.db.models.deletion.DO_NOTHING, to='AppPPDA.medida')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='AppPPDA.plan')),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='planes_referencia',
            field=models.ManyToManyField(through='AppPPDA.MedidaPlan', to='AppPPDA.plan'),
        ),
    ]
