# Generated by Django 5.1.5 on 2025-01-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPPDA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='tipo',
            field=models.IntegerField(choices=[('1', 'Regulación'), ('2', 'Fomento de actividades económicas'), ('3', 'Beneficios para impulsar acciones de interés general'), ('4', 'Estudios'), ('5', 'Educación y difusión'), ('6', 'Política Pública')]),
        ),
    ]
