# Generated by Django 5.1.5 on 2025-01-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPPDA', '0002_alter_medida_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='estado',
        ),
    ]
